### PR TITLE
GitHub Action

### PR DESCRIPTION
**Pull request by amireshoon**
Added GitHub action for building frontend and testing that it build status on 3 versions of node (12, 14, 15).

Action triggers on push and pr to master and develop

### CODE REVIEW

**Review by yazdanv — APPROVED** [review]

**Comment by yazdanv** [comment]
Hi, thanks for your contribution
it would be nice if we could have deployment (for develop branch) on github pages too, i'm unfamiliar with the process but if you would like to do it and need changes in the setting let me know

**Comment by amireshoon** [comment]
Hey, I will work on that. THank you for letting me know.

**Comment by amireshoon** [comment]
Github pages are now working but there are some 404 errors and some network errors and as I'm not a Front-end developer I don't know them. But anytime you give a hint to me I resolve them. But without them, Github pages are working nicely.

Preview (https://amireshoon.github.io/website/)[https://amireshoon.github.io/website/]

**Review by yazdanv — APPROVED** [review]

**Comment by yazdanv** [comment]
thanks for the edit, we probably need to allow cors headers for github pages url

**Pull request merged**
